import type {
  Company,
  Location,
  Contact,
  CompanyWithRelations,
  SyncStatus,
  SearchRun,
} from "@pi/contracts";

// ---------------------------------------------------------------------------
// Companies — 8 real QLD energy/mining/infrastructure companies
// ---------------------------------------------------------------------------

export const FIXTURE_COMPANIES: Company[] = [
  {
    companyId: "comp-csenergy",
    abn: "54078848745",
    companyName: "CS Energy Ltd",
    normalizedName: "cs energy ltd",
    tradingName: "CS Energy",
    website: "https://www.csenergy.com.au",
    industry: "Electricity Generation",
    abnStatus: "Active",
    status: "APPROVED",
    industryFit: "TARGET",
    priority: 1,
    source: "ABR",
    lastVerified: "2026-08-15T00:00:00Z",
    lastModified: "2026-08-15T00:00:00Z",
  },
  {
    companyId: "comp-stanwell",
    abn: "37078848674",
    companyName: "Stanwell Corporation Limited",
    normalizedName: "stanwell corporation limited",
    tradingName: "Stanwell",
    website: "https://www.stanwell.com",
    industry: "Electricity Generation",
    abnStatus: "Active",
    status: "APPROVED",
    industryFit: "TARGET",
    priority: 1,
    source: "ABR",
    lastVerified: "2026-08-10T00:00:00Z",
    lastModified: "2026-08-10T00:00:00Z",
  },
  {
    companyId: "comp-downer",
    abn: "97003872848",
    companyName: "Downer EDI Limited",
    normalizedName: "downer edi limited",
    tradingName: "Downer",
    website: "https://www.downergroup.com",
    industry: "Engineering Services",
    abnStatus: "Active",
    status: "REVIEW",
    industryFit: "TARGET",
    priority: 2,
    source: "ABR",
    lastVerified: "2026-07-20T00:00:00Z",
    lastModified: "2026-07-20T00:00:00Z",
  },
  {
    companyId: "comp-thiess",
    abn: "87010221486",
    companyName: "Thiess Pty Ltd",
    normalizedName: "thiess pty ltd",
    tradingName: "Thiess",
    website: "https://www.thiess.com",
    industry: "Mining Services",
    abnStatus: "Active",
    status: "APPROVED",
    industryFit: "TARGET",
    priority: 1,
    source: "ABR",
    lastVerified: "2026-08-01T00:00:00Z",
    lastModified: "2026-08-01T00:00:00Z",
  },
  {
    companyId: "comp-sunmetals",
    abn: "50074014733",
    companyName: "Sun Metals Corporation Pty Ltd",
    normalizedName: "sun metals corporation pty ltd",
    tradingName: "Sun Metals",
    website: "https://www.sunmetals.com.au",
    industry: "Zinc Refining",
    abnStatus: "Active",
    status: "VERIFYING",
    industryFit: "TARGET",
    priority: 2,
    source: "PUBLIC_SEARCH",
    lastVerified: "2026-06-15T00:00:00Z",
    lastModified: "2026-06-15T00:00:00Z",
  },
  {
    companyId: "comp-ergon",
    abn: "50087646062",
    companyName: "Ergon Energy Corporation Limited",
    normalizedName: "ergon energy corporation limited",
    tradingName: "Ergon Energy",
    website: "https://www.ergon.com.au",
    industry: "Electricity Distribution",
    abnStatus: "Active",
    status: "APPROVED",
    industryFit: "TARGET",
    priority: 1,
    source: "ABR",
    lastVerified: "2026-08-12T00:00:00Z",
    lastModified: "2026-08-12T00:00:00Z",
  },
  {
    companyId: "comp-gladports",
    abn: "96263788242",
    companyName: "Gladstone Ports Corporation Limited",
    normalizedName: "gladstone ports corporation limited",
    tradingName: "Gladstone Ports",
    website: "https://www.gpcl.com.au",
    industry: "Port Operations",
    abnStatus: "Active",
    status: "REVIEW",
    industryFit: "ADJACENT",
    priority: 3,
    source: "OFFICIAL_WEBSITE",
    lastVerified: "2026-07-05T00:00:00Z",
    lastModified: "2026-07-05T00:00:00Z",
  },
  {
    companyId: "comp-aurizon",
    abn: "14146335622",
    companyName: "Aurizon Holdings Limited",
    normalizedName: "aurizon holdings limited",
    tradingName: "Aurizon",
    website: "https://www.aurizon.com.au",
    industry: "Rail Freight",
    abnStatus: "Active",
    status: "APPROVED",
    industryFit: "ADJACENT",
    priority: 2,
    source: "ABR",
    lastVerified: "2026-08-05T00:00:00Z",
    lastModified: "2026-08-05T00:00:00Z",
  },
];

// ---------------------------------------------------------------------------
// Locations
// ---------------------------------------------------------------------------

export const FIXTURE_LOCATIONS: Location[] = [
  {
    locationId: "loc-callide",
    companyId: "comp-csenergy",
    siteName: "Callide Power Station",
    locationType: "PLANT",
    address: "Callide Power Station Rd",
    suburb: "Biloela",
    state: "QLD",
    postcode: "4715",
    lat: -24.3428,
    lng: 150.5036,
    verificationStatus: "VERIFIED",
    lastVerified: "2026-08-15T00:00:00Z",
    lastModified: "2026-08-15T00:00:00Z",
  },
  {
    locationId: "loc-kogan",
    companyId: "comp-csenergy",
    siteName: "Kogan Creek Power Station",
    locationType: "PLANT",
    address: "Kogan Creek Rd",
    suburb: "Brigalow",
    state: "QLD",
    postcode: "4412",
    lat: -26.9317,
    lng: 150.7606,
    verificationStatus: "VERIFIED",
    lastVerified: "2026-08-15T00:00:00Z",
    lastModified: "2026-08-15T00:00:00Z",
  },
  {
    locationId: "loc-tarong",
    companyId: "comp-stanwell",
    siteName: "Tarong Power Station",
    locationType: "PLANT",
    address: "Tarong Power Station Rd",
    suburb: "Tarong",
    state: "QLD",
    postcode: "4615",
    lat: -26.7667,
    lng: 151.9167,
    verificationStatus: "VERIFIED",
    lastVerified: "2026-08-10T00:00:00Z",
    lastModified: "2026-08-10T00:00:00Z",
  },
  {
    locationId: "loc-stanwell-ps",
    companyId: "comp-stanwell",
    siteName: "Stanwell Power Station",
    locationType: "PLANT",
    address: "Stanwell Power Station Rd",
    suburb: "Stanwell",
    state: "QLD",
    postcode: "4702",
    lat: -23.4978,
    lng: 150.3267,
    verificationStatus: "VERIFIED",
    lastVerified: "2026-08-10T00:00:00Z",
    lastModified: "2026-08-10T00:00:00Z",
  },
  {
    locationId: "loc-downer-bne",
    companyId: "comp-downer",
    siteName: "Downer Brisbane Office",
    locationType: "OFFICE",
    address: "363 Adelaide St",
    suburb: "Brisbane City",
    state: "QLD",
    postcode: "4000",
    lat: -27.4667,
    lng: 153.0267,
    verificationStatus: "VERIFIED",
    lastVerified: "2026-07-20T00:00:00Z",
    lastModified: "2026-07-20T00:00:00Z",
  },
  {
    locationId: "loc-thiess-mackay",
    companyId: "comp-thiess",
    siteName: "Thiess Mackay Operations",
    locationType: "MINE",
    address: "Nebo Rd",
    suburb: "Mackay",
    state: "QLD",
    postcode: "4740",
    lat: -21.1411,
    lng: 149.1861,
    verificationStatus: "VERIFIED",
    lastVerified: "2026-08-01T00:00:00Z",
    lastModified: "2026-08-01T00:00:00Z",
  },
  {
    locationId: "loc-sunmetals-townsville",
    companyId: "comp-sunmetals",
    siteName: "Sun Metals Zinc Refinery",
    locationType: "PLANT",
    address: "Stuart Dr",
    suburb: "Stuart",
    state: "QLD",
    postcode: "4811",
    lat: -19.3322,
    lng: 146.8400,
    verificationStatus: "UNVERIFIED",
    lastVerified: "2026-06-15T00:00:00Z",
    lastModified: "2026-06-15T00:00:00Z",
  },
  {
    locationId: "loc-ergon-tville",
    companyId: "comp-ergon",
    siteName: "Ergon Energy Townsville Depot",
    locationType: "DEPOT",
    address: "Woolcock St",
    suburb: "Townsville",
    state: "QLD",
    postcode: "4810",
    lat: -19.2833,
    lng: 146.7833,
    verificationStatus: "VERIFIED",
    lastVerified: "2026-08-12T00:00:00Z",
    lastModified: "2026-08-12T00:00:00Z",
  },
  {
    locationId: "loc-gladports-rg3",
    companyId: "comp-gladports",
    siteName: "Gladstone Port RG Tanna Terminal",
    locationType: "PLANT",
    address: "Port Access Rd",
    suburb: "Gladstone",
    state: "QLD",
    postcode: "4680",
    lat: -23.8500,
    lng: 151.2700,
    verificationStatus: "VERIFIED",
    lastVerified: "2026-07-05T00:00:00Z",
    lastModified: "2026-07-05T00:00:00Z",
  },
  {
    locationId: "loc-aurizon-bne",
    companyId: "comp-aurizon",
    siteName: "Aurizon Brisbane HQ",
    locationType: "OFFICE",
    address: "900 Ann St",
    suburb: "Fortitude Valley",
    state: "QLD",
    postcode: "4006",
    lat: -27.4536,
    lng: 153.0379,
    verificationStatus: "VERIFIED",
    lastVerified: "2026-08-05T00:00:00Z",
    lastModified: "2026-08-05T00:00:00Z",
  },
  {
    locationId: "loc-aurizon-mackay",
    companyId: "comp-aurizon",
    siteName: "Aurizon Jilalan Rail Yard",
    locationType: "DEPOT",
    address: "Jilalan Rd",
    suburb: "Jilalan",
    state: "QLD",
    postcode: "4740",
    lat: -21.2000,
    lng: 149.1000,
    verificationStatus: "VERIFIED",
    lastVerified: "2026-08-05T00:00:00Z",
    lastModified: "2026-08-05T00:00:00Z",
  },
];

// ---------------------------------------------------------------------------
// Contacts
// ---------------------------------------------------------------------------

export const FIXTURE_CONTACTS: Contact[] = [
  {
    contactId: "cnt-csenergy-gm",
    companyId: "comp-csenergy",
    locationId: "loc-callide",
    name: "Andrew Walker",
    position: "General Manager - Operations",
    roleBucket: "General Manager",
    rolePriority: "PRIORITY",
    businessEmail: "andrew.walker@csenergy.com.au",
    mobile: "0412 345 678",
    contactStatus: "VERIFIED",
    lastVerified: "2026-08-15T00:00:00Z",
    lastModified: "2026-08-15T00:00:00Z",
  },
  {
    contactId: "cnt-csenergy-mm",
    companyId: "comp-csenergy",
    locationId: "loc-callide",
    name: "Sarah Mitchell",
    position: "Maintenance Manager",
    roleBucket: "Maintenance Manager",
    rolePriority: "PRIORITY",
    businessEmail: "sarah.mitchell@csenergy.com.au",
    contactStatus: "VERIFIED",
    lastVerified: "2026-08-15T00:00:00Z",
    lastModified: "2026-08-15T00:00:00Z",
  },
  {
    contactId: "cnt-stanwell-pm",
    companyId: "comp-stanwell",
    locationId: "loc-tarong",
    name: "David Thompson",
    position: "Plant Manager",
    roleBucket: "Plant Manager",
    rolePriority: "PRIORITY",
    businessEmail: "david.thompson@stanwell.com",
    mobile: "0423 456 789",
    contactStatus: "APPROVED",
    lastVerified: "2026-08-10T00:00:00Z",
    lastModified: "2026-08-10T00:00:00Z",
  },
  {
    contactId: "cnt-stanwell-proc",
    companyId: "comp-stanwell",
    locationId: "loc-stanwell-ps",
    name: "Lisa Chen",
    position: "Procurement Manager",
    roleBucket: "Procurement Manager",
    rolePriority: "PRIORITY",
    businessEmail: "lisa.chen@stanwell.com",
    contactStatus: "VERIFIED",
    lastVerified: "2026-08-10T00:00:00Z",
    lastModified: "2026-08-10T00:00:00Z",
  },
  {
    contactId: "cnt-downer-om",
    companyId: "comp-downer",
    locationId: "loc-downer-bne",
    name: "Mark Reynolds",
    position: "Operations Manager - QLD",
    roleBucket: "Operations Manager",
    rolePriority: "PRIORITY",
    businessEmail: "mark.reynolds@downergroup.com",
    mobile: "0434 567 890",
    contactStatus: "NEW",
    lastVerified: "2026-07-20T00:00:00Z",
    lastModified: "2026-07-20T00:00:00Z",
  },
  {
    contactId: "cnt-thiess-sm",
    companyId: "comp-thiess",
    locationId: "loc-thiess-mackay",
    name: "James O'Brien",
    position: "Site Manager - Bowen Basin",
    roleBucket: "Site Manager",
    rolePriority: "PRIORITY",
    businessEmail: "james.obrien@thiess.com",
    mobile: "0445 678 901",
    contactStatus: "APPROVED",
    lastVerified: "2026-08-01T00:00:00Z",
    lastModified: "2026-08-01T00:00:00Z",
  },
  {
    contactId: "cnt-thiess-safety",
    companyId: "comp-thiess",
    locationId: "loc-thiess-mackay",
    name: "Karen White",
    position: "Safety Manager",
    roleBucket: "Safety Manager",
    rolePriority: "SECONDARY",
    businessEmail: "karen.white@thiess.com",
    contactStatus: "VERIFIED",
    lastVerified: "2026-08-01T00:00:00Z",
    lastModified: "2026-08-01T00:00:00Z",
  },
  {
    contactId: "cnt-sunmetals-eng",
    companyId: "comp-sunmetals",
    locationId: "loc-sunmetals-townsville",
    name: "Robert Zhang",
    position: "Engineering Manager",
    roleBucket: "Engineering Manager",
    rolePriority: "PRIORITY",
    businessEmail: "robert.zhang@sunmetals.com.au",
    contactStatus: "NEW",
    lastVerified: "2026-06-15T00:00:00Z",
    lastModified: "2026-06-15T00:00:00Z",
  },
  {
    contactId: "cnt-ergon-fleet",
    companyId: "comp-ergon",
    locationId: "loc-ergon-tville",
    name: "Tony Moretti",
    position: "Fleet Manager - North QLD",
    roleBucket: "Fleet Manager",
    rolePriority: "SECONDARY",
    businessEmail: "tony.moretti@ergon.com.au",
    mobile: "0456 789 012",
    contactStatus: "VERIFIED",
    lastVerified: "2026-08-12T00:00:00Z",
    lastModified: "2026-08-12T00:00:00Z",
  },
  {
    contactId: "cnt-gladports-md",
    companyId: "comp-gladports",
    locationId: "loc-gladports-rg3",
    name: "Helen Murray",
    position: "Managing Director",
    roleBucket: "Managing Director",
    rolePriority: "PRIORITY",
    businessEmail: "helen.murray@gpcl.com.au",
    contactStatus: "VERIFIED",
    lastVerified: "2026-07-05T00:00:00Z",
    lastModified: "2026-07-05T00:00:00Z",
  },
  {
    contactId: "cnt-aurizon-logm",
    companyId: "comp-aurizon",
    locationId: "loc-aurizon-bne",
    name: "Phil Dawson",
    position: "Logistics Manager - Coal",
    roleBucket: "Logistics Manager",
    rolePriority: "SECONDARY",
    businessEmail: "phil.dawson@aurizon.com.au",
    contactStatus: "APPROVED",
    lastVerified: "2026-08-05T00:00:00Z",
    lastModified: "2026-08-05T00:00:00Z",
  },
  {
    contactId: "cnt-aurizon-maint",
    companyId: "comp-aurizon",
    locationId: "loc-aurizon-mackay",
    name: "Bec Nguyen",
    position: "Maintenance Manager - Rolling Stock",
    roleBucket: "Maintenance Manager",
    rolePriority: "PRIORITY",
    businessEmail: "bec.nguyen@aurizon.com.au",
    mobile: "0467 890 123",
    contactStatus: "VERIFIED",
    lastVerified: "2026-08-05T00:00:00Z",
    lastModified: "2026-08-05T00:00:00Z",
  },
];

// ---------------------------------------------------------------------------
// Sync status
// ---------------------------------------------------------------------------

export const FIXTURE_SYNC_STATUS: SyncStatus = {
  state: "SYNCED",
  lastSync: "2026-09-01T10:30:00Z",
  companiesCount: 8,
  locationsCount: 11,
  contactsCount: 12,
  errors: [],
};

// ---------------------------------------------------------------------------
// Search runs
// ---------------------------------------------------------------------------

export const FIXTURE_SEARCH_RUNS: SearchRun[] = [
  {
    searchId: "search-001",
    postcode: "4702",
    industry: "Electricity Generation",
    roles: ["Plant Manager", "Maintenance Manager", "Operations Manager"],
    status: "completed",
    startedAt: "2026-08-10T09:00:00Z",
    completedAt: "2026-08-10T09:04:32Z",
    companiesFound: 2,
    contactsFound: 4,
  },
  {
    searchId: "search-002",
    postcode: "4740",
    industry: "Mining Services",
    roles: ["Site Manager", "Safety Manager", "Procurement Manager"],
    status: "completed",
    startedAt: "2026-08-01T14:00:00Z",
    completedAt: "2026-08-01T14:03:18Z",
    companiesFound: 2,
    contactsFound: 3,
  },
  {
    searchId: "search-003",
    postcode: "4000",
    industry: "Engineering Services",
    roles: ["Operations Manager", "General Manager"],
    status: "running",
    startedAt: "2026-09-01T08:15:00Z",
    companiesFound: 1,
    contactsFound: 0,
  },
];

// ---------------------------------------------------------------------------
// Builder: companies with relations
// ---------------------------------------------------------------------------

export function buildCompaniesWithRelations(): CompanyWithRelations[] {
  return FIXTURE_COMPANIES.map((company) => ({
    ...company,
    locations: FIXTURE_LOCATIONS.filter(
      (loc) => loc.companyId === company.companyId
    ),
    contacts: FIXTURE_CONTACTS.filter(
      (cnt) => cnt.companyId === company.companyId
    ),
  }));
}
